version: '1'
services:
  ftbpubmanager:
    container_name: ftbpubmanager
    image: ftbpubmanager
    restart: always
    build: .
    ports:
      - "5001:5001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'